server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

auth:
  jwt:
    secret: ${JWT_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
    exp:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}

image:
  upload:
    dir: ${IMAGE_DRI}